"""
Prompts package for the stock picker system.
Contains system prompts and input templates for all agents.
"""

from .query_processor_prompts import QUERY_PROCESSOR_SYSTEM_PROMPT, QUERY_PROCESSOR_INPUT_TEMPLATE
from .stock_picker_prompts import STOCK_PICKER_SYSTEM_PROMPT, STOCK_PICKER_INPUT_TEMPLATE
from .analyzer_prompts import ANALYZER_SYSTEM_PROMPT, ANALYZER_INPUT_TEMPLATE
from .product_bundler_prompts import PRODUCT_BUNDLER_SYSTEM_PROMPT, PRODUCT_BUNDLER_INPUT_TEMPLATE

__all__ = [
    'QUERY_PROCESSOR_SYSTEM_PROMPT',
    'QUERY_PROCESSOR_INPUT_TEMPLATE',
    'STOCK_PICKER_SYSTEM_PROMPT',
    'STOCK_PICKER_INPUT_TEMPLATE',
    'ANALYZER_SYSTEM_PROMPT',
    'ANALYZER_INPUT_TEMPLATE',
    'PRODUCT_BUNDLER_SYSTEM_PROMPT',
    'PRODUCT_BUNDLER_INPUT_TEMPLATE'
] 