
#ifndef ICUEAUTOMATIONSDK_EXPORT_H
#define ICUEAUTOMATIONSDK_EXPORT_H

#ifdef ICUEAUTOMATIONSDK_STATIC_DEFINE
#  define ICUEAUTOMATIONSDK_EXPORT
#  define ICUEAUTOMATIONSDK_NO_EXPORT
#else
#  ifndef ICUEAUTOMATIONSDK_EXPORT
#    ifdef iCUEAutomationSDK_EXPORTS
        /* We are building this library */
#      define ICUEAUTOMATIONSDK_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define ICUEAUTOMATIONSDK_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef ICUEAUTOMATIONSDK_NO_EXPORT
#    define ICUEAUTOMATIONSDK_NO_EXPORT 
#  endif
#endif

#ifndef ICUEAUTOMATIONSDK_DEPRECATED
#  define ICUEAUTOMATIONSDK_DEPRECATED __declspec(deprecated)
#endif

#ifndef ICUEAUTOMATIONSDK_DEPRECATED_EXPORT
#  define ICUEAUTOMATIONSDK_DEPRECATED_EXPORT ICUEAUTOMATIONSDK_EXPORT ICUEAUTOMATIONSDK_DEPRECATED
#endif

#ifndef ICUEAUTOMATIONSDK_DEPRECATED_NO_EXPORT
#  define ICUEAUTOMATIONSDK_DEPRECATED_NO_EXPORT ICUEAUTOMATIONSDK_NO_EXPORT ICUEAUTOMATIONSDK_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef ICUEAUTOMATIONSDK_NO_DEPRECATED
#    define ICUEAUTOMATIONSDK_NO_DEPRECATED
#  endif
#endif

#endif /* ICUEAUTOMATIONSDK_EXPORT_H */
